name: Install Docker on EC2

on:
  push:
    branches:
      - main

jobs:
  install-docker:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and install Docker
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USERNAME}@${EC2_HOST} '
            sudo apt-get update
            sudo apt-get -y --fix-broken install docker.io
          '
