name: Install Docker on EC2 and Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  install-docker-build-image:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and install Docker
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USERNAME}@${EC2_HOST} '
            sudo apt-get update
            sudo apt-get -y --fix-broken install docker.io
      - name: Clone the repository 
        run: git clone git@github.com:Tushar-ops23/angularjs-application.git

      - name: Build Docker image
        run: |
          cd angularjs-application
          docker build -t angularjs-application .
          docker run -d -p 80:80 angularjs-application
      
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERU_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERU_PASS }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: docker build -t angularjs-application .

      - name: Tag and push Docker image
        run: |
          docker tag angularjs $DOCKER_USERNAME/angularjs-application:latest
          docker push $DOCKER_USERNAME/angularjs-application:latest
