name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${EC2_USERNAME}@${EC2_HOST} '
            sudo apt-get update
            sudo apt-get install docker.io -y'

      - name: Build Docker image
        run: docker build -t angular .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERU_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERU_PASS }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push your_image_name:latest

      - name: Deploy container to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${EC2_USERNAME}@${EC2_HOST} '
            docker stop your_container_name || true
            docker rm your_container_name || true
            docker pull your_image_name:latest
            docker run -d -p 80:80 --name fuckoff angular'
